name: jaspr_falmodel
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  dart_falmodel:
    path: /Users/nonthawit/Data/Github/FalconX/dart-falconx/dart_falmodel
  jaspr_faltool:
    path: ../jaspr_faltool

dev_dependencies:
  build_runner: ^2.7.0
  lints: ^6.0.0
  test: ^1.26.3
  very_good_analysis: ^9.0.0
