name: jaspr_faltool
description: A tools library for Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  ansicolor: ^2.0.3

  dart_faltool:
    path: /Users/nonthawit/Data/Github/FalconX/dart-falconx/dart_faltool

  jaspr: ^0.20.0
  universal_web: ^1.1.1

dev_dependencies:
  build_runner: ^2.7.0
  lints: ^6.0.0
  test: ^1.26.3
  very_good_analysis: ^9.0.0
