name: jaspr_falconnect
description: A new Flutter package project.
version: 1.0.5
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  dart_falconnect:
    git:
      url: https://github.com/Nextzy/dart-falconx.git
      path: dart_falconnect
      ref: fd77887b41c32f305708f8884995c6ca6a323aa6
#    path: /Users/nonthawit/Data/Github/FalconX/dart-falconx/dart_falconnect

  jaspr_falmodel:
    path: ../jaspr_falmodel
  jaspr_faltool:
    path: ../jaspr_faltool

  #PLATFORM: All
  ansicolor: ^2.0.3
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.8.0
  test: ^1.26.3
  lints: ^6.0.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  very_good_analysis: ^10.0.0
