name: jaspr_falconx
description: A dart falcon package.
version: 1.0.4
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  jaspr_falconnect:
    path: ../jaspr_falconnect
  jaspr_falmodel:
    path: ../jaspr_falmodel
  jaspr_falmonitor:
    path: ../jaspr_falmonitor
  jaspr_falkit:
    path: ../jaspr_falkit
  jaspr_falstore:
    path: ../jaspr_falstore
  jaspr_faltool:
    path: ../jaspr_faltool

  jaspr: ^0.21.2
  jaspr_router: ^0.7.3
  jaspr_riverpod: ^0.3.23
  universal_web: ^1.1.1

dev_dependencies:
  build_runner: ^2.8.0
  test: ^1.26.3
  very_good_analysis: ^10.0.0
