name: jaspr_falmonitor
publish_to: none
description: A monitor library.
version: 0.0.1

environment:
  sdk: ">=3.10.0 <4.0.0"

resolution: workspace

dependencies:
  jaspr_faltool:
    path: ../jaspr_faltool
  sentry: ^9.16.0
  universal_web: ^1.1.1+1
  jaspr: ^0.22.4

dev_dependencies:
  build_runner: ^2.13.1
  lints: ^6.1.0
  very_good_analysis: ^10.2.0