name: jaspr_falmonitor
description: A monitor library.
version: 0.0.1

environment:
  sdk: ">=3.9.0 <4.0.0"

resolution: workspace

dependencies:
  jaspr_faltool:
    path: ../jaspr_faltool
  sentry: ^9.6.0
  universal_web: ^1.1.1
  jaspr: ^0.21.1

dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
  very_good_analysis: ^9.0.0