name: jaspr_falwind
description: Tailwind and DaisyUI integration for Jaspr.
version: 1.0.3

topics:
  - jaspr
  - web
  - html
  - css

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  build: ^4.0.0
  build_modules: ^5.0.17
  glob: ^2.1.3
  path: ^1.9.1


dev_dependencies:
  build_runner: ^2.8.0
  lints: ^6.0.0
